# Настройки тайтлов при возрождении
title: "<gradient:#ff0000:#ffff00>Возрождение</gradient>"
subtitle: "<gray>Вы были воскрешены</gray>"

# Настройки звука (формат: название_звука,громкость,высота
# Пример: ENTITY_PLAYER_LEVELUP,1.0,1.0
# Или none для отключения
sound: "ENTITY_PLAYER_LEVELUP,1.0,1.0"

# Время в тиках (20 тиков = 1 секунда)
times:
  fade_in: 10 # Появление
  stay: 40    # Длительность показа
  fade_out: 10 # Исчезновение